config/routes.rb
FriendOverFood::Application.routes.draw do

  resources :clubs do
    member do
      post 'join'
      post 'approve_membership'
      post 'deny_membership'
    end
  end

  resources :admins do
    member do
    end
  end

  resources :users do
    member do
      get :lunch_confirmation
      post 'verify'
      post 'unverify'
    end
  end

  resources :sessions
  resources :lunches

  resources :pending_memberships
  resources :memberships do
    member do
      post 'make_admin'
    end
  end
  
  get "sign_out" => "sessions#destroy", :as => "sign_out"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match 'contact' => 'home#contact'
  match 'about' => 'home#about'
  match 'faq' => 'home#faq'

  root :to => 'home#index'

end

app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessible :name, :description
  
  has_many :lunches

  has_many :pending_memberships, dependent: :destroy

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates_presence_of :name
  validates :description, :length => { :maximum => 200 }
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  # GET /clubs
  # GET /clubs.json

  def approve_membership
    @pm = PendingMembership.find(params[:id])
    @club = @pm.club
    m = Membership.new
    m.club_id = @pm.club_id
    m.user_id = @pm.user_id

    if m.save
      @pm.destroy
      UserMailer.verified_membership(@pm).deliver
      redirect_to club_path(@club)
    end
  end

  def deny_membership
    @pm = PendingMembership.find(params[:id])
    @club = @pm.club
    @pm.destroy
    redirect_to club_path(@club)
  end

  def join
    @club = Club.find(params[:id])
    
    if current_user
      m = PendingMembership.new
      m.user_id = current_user.id
      # Needed since some PendingMemberships don't have User IDs yet and this keeps view code consistent
      m.user_first_name = current_user.first_name
      m.user_last_name = current_user.last_name
      m.user_email = current_user.email
      m.club_id = @club.id
      m.save
      UserMailer.admin_verification(m).deliver
      flash[:notice] = "Request to join #{@club.name} submitted. You'll be notified once your request is approved."
      redirect_to user_path(current_user.id)
    else
      flash[:notice] = 'Must be signed in to join club.'
      redirect_to clubs_path
    end
  end

  def index
    @clubs = Club.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clubs }
    end
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @club = Club.find(params[:id])
    @current_user_membership = Membership.where(club_id: @club, user_id: current_user).first

    if current_user.clubs.include? @club
      if @current_user_membership.is_admin == true
        authorize! :manage, @club
      end
    else
      authorize! :read, @club
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @club }
    end
  end

  # GET /clubs/new
  # GET /clubs/new.json
  def new
    @club = Club.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @club }
    end
  end

  # GET /clubs/1/edit
  def edit
    @club = Club.find(params[:id])
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(params[:club])

    respond_to do |format|
      if @club.save
        @membership = Membership.new
        @membership.club_id = @club.id
        @membership.user_id = current_user.id
        @membership.is_admin = true
        @membership.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render json: @club, status: :created, location: @club }
      else
        format.html { render action: "new" }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clubs/1
  # PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])

    respond_to do |format|
      if @club.update_attributes(params[:club])
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end
end

app/views/clubs/_form.html.haml
= form_for @club do |f|
  - if @club.errors.any?
    #error_explanation
      %h2= "#{pluralize(@club.errors.count, "error")} prohibited this club from being saved:"
      %ul
        - @club.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name, placeholder: "Club Name"
  .field
    = f.text_area :description, placeholder: "Short Club Description", class: "text"
    %label{:for => "description"} 
      *Maximum 200 characters

  .actions
    = f.submit 'Save'

app/views/clubs/edit.html.haml
%h1 Editing club

.center-box
  .is-inline-block
    = render 'form'

= link_to 'Show', @club
\|
= link_to 'Back', clubs_path

app/views/clubs/index.html.haml
%h1 All Clubs

%table.admin-table
  %tr
    %th
    %th
    %th

  - @clubs.each do |club|
    %tr
      %td
        %strong 
          %a{:href => "#{club_path(club.id)}"} 
            = club.name
      %td= club.description
      - if current_user.clubs.include? @club == false
        %td= link_to 'Join', join_club_path(club), method: :post
      %td= link_to 'More Info', club
      / # %td= link_to 'Edit', edit_club_path(club)
      / # %td= link_to 'Destroy', club, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

%p 
  = link_to 'Create New Club', new_club_path, class: "submit"

app/views/clubs/new.html.haml
%h1 Create a New Club

.center-box
  .is-inline-block
    = render 'form'

= link_to 'Back', clubs_path

app/views/clubs/show.html.haml
.profile.is-left

  %h1 
    = @club.name

  %p 
    = @club.description

  %span.is-block.is-ta-center
    = link_to 'Back to Clubs List', clubs_path, class: "is-inline-block"

    -if can? :update, @club
      \|
      = link_to 'Edit Description', edit_club_path(@club), class: "is-inline-block"
      \|
      = link_to 'Delete Club', @club, method: :delete, data: { confirm: 'Are you sure?' }


    - if Membership.where(club_id: @club, user_id: current_user.id).first != nil
      %p.clear
      = link_to "Leave #{@club.name}", Membership.where(club_id: @club, user_id: current_user.id).first, method: :delete, data: { confirm: "Are you sure you want to leave #{@club.name}?" }, class: "is-inline-block"

.clubs-list.is-left

  %h2 Club Admins

  - @club.memberships.where(is_admin: true).each do |m|
    %p.club-member 
      %strong
        = m.user.first_name + ' ' + m.user.last_name
      -if can? :manage, @club
        %span 
          \|
        = link_to 'Remove', membership_path(m), method: :delete

  - if @club.memberships.where(is_admin: nil).length > 0
    %h2 Club Members

    - @club.memberships.where(is_admin: nil).each do |m|
      %p.club-member 
        %strong
          = m.user.first_name + ' ' + m.user.last_name
        -if can? :manage, @club
          %span 
            \|
          = link_to 'Remove', membership_path(m), method: :delete
          
          %span 
            \|
          = link_to "Make Admin", make_admin_membership_path(m), method: :post


  -if can? :manage, @club
    -if @club.pending_memberships.where(PendingMembership.arel_table[:user_id].not_eq(nil)).length > 0
      %h2 Pending Members

      - @club.pending_memberships.where(PendingMembership.arel_table[:user_id].not_eq(nil)).each do |p|
        %p.club-member 
          %strong
            = p.user_first_name + ' ' + p.user_last_name
          %span 
            \|
          = link_to 'Approve Membership', approve_membership_club_path(p), method: :post
          %span 
            \|
          = link_to 'Deny Membership', deny_membership_club_path(p), method: :post

  %p.is-block.is-ta-center 
    - if current_user.clubs.include? @club

      = link_to "Invite people to join #{@club.name}", new_pending_membership_path(:club => @club.id), class: "is-ta-center is-inline-block submit"
    - else 
      / join club link


  %br/ 
  %br/ 

  - unless current_user.clubs.include? @club
    = link_to "Join #{@club.name}", join_club_path(@club), method: :post, class: "is-ta-center is-inline-block submit"