config/routes.rb
FriendOverFood::Application.routes.draw do

  resources :clubs do
    member do
      post 'join'
      post 'approve_membership'
      post 'deny_membership'
    end
  end

  resources :admins do
    member do
    end
  end

  resources :users do
    member do
      get :lunch_confirmation
      post 'verify'
      post 'unverify'
    end
  end

  resources :sessions
  resources :lunches

  resources :pending_memberships
  resources :memberships do
    member do
      post 'make_admin'
    end
  end
  
  get "sign_out" => "sessions#destroy", :as => "sign_out"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match 'contact' => 'home#contact'
  match 'about' => 'home#about'
  match 'faq' => 'home#faq'

  root :to => 'home#index'

end

app/views/admins/_form.html.haml
= form_for @admin do |f|
  - if @admin.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @admin.errors.full_messages
          %li= message

  .field
    = f.text_field :email, placeholder: "Email"
  .field
    = f.password_field :password, placeholder: "Password"
  .field
    = f.password_field :password_confirmation, placeholder: "Confirm Password"
  .actions= f.submit

app/views/admins/edit.html.haml
%h1 Editing admin

= render 'form'

= link_to 'Show', @admin
\|
= link_to 'Back', admins_path

app/views/admins/index.html.haml
%h1 Listing admins

%table
  %tr
    %th
    %th
    %th

  - @admins.each do |admin|
    %tr
      %td= link_to 'Show', admin
      %td= link_to 'Edit', edit_admin_path(admin)
      %td= link_to 'Destroy', admin, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Admin', new_admin_path

app/views/admins/new.html.haml
%h1 New admin

= render 'form'

= link_to 'Back', admins_path

app/views/admins/show.html.haml
.admin
  %h1 All Users

  %table.admin-table
    %tr
      %th First Name
      %th Last Name
      %th City
      %th.email 
        %a.toggle-email{:href => "#"} 
          Email
      %th
      %th
      %th
      %th
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= user.city
        %td.email= user.email
        %td= link_to 'View', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }
        %td
          - if (user.is_verified == nil) || (user.is_verified == false)
            = link_to 'Verify', verify_user_path(user), method: :post
          - elsif user.is_verified == true
            = link_to 'Unverify', unverify_user_path(user), method: :post



:javascript
  $(".toggle-email").click(function(e){
    e.preventDefault();
    $("td").toggle();
    $("th").toggle();
    $(".email").show();
  });