config/routes.rb
FriendOverFood::Application.routes.draw do

  resources :clubs do
    member do
      post 'join'
      post 'approve_membership'
      post 'deny_membership'
    end
  end

  resources :admins do
    member do
    end
  end

  resources :users do
    member do
      get :lunch_confirmation
      post 'verify'
      post 'unverify'
    end
  end

  resources :sessions
  resources :lunches

  resources :pending_memberships
  resources :memberships do
    member do
      post 'make_admin'
    end
  end
  
  get "sign_out" => "sessions#destroy", :as => "sign_out"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match 'contact' => 'home#contact'
  match 'about' => 'home#about'
  match 'faq' => 'home#faq'

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :city, :is_verified, :memberships_attributes, :pending_memberships_attributes

  has_secure_password

  has_many :lunches
  has_many :lunchers, through: :lunches
  has_many :inverse_lunches, class_name: "Lunch", foreign_key: "luncher_id"
  has_many :inverse_lunchers, through: :inverse_lunches, source: :user

  has_many :pending_memberships, dependent: :destroy
  accepts_nested_attributes_for :pending_memberships
  # validates_presence_of :pending_memberships, on: :create


  has_many :memberships, dependent: :destroy
  has_many :clubs, through: :memberships
  accepts_nested_attributes_for :memberships


  validates_confirmation_of :password, :on => :create
  validates_length_of :password, :minimum => 6, :on => :create
  validates_presence_of :password, :on => :create

  validates_presence_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_uniqueness_of :email

  validates_presence_of :first_name
  validates_presence_of :last_name

  before_save do
    self.email = self.email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before filter to load the resource into an instance variable and authorize it for every action
  # load_and_authorize_resource

  def verify
    @user = User.find(params[:id])
    @user.update_attribute(:is_verified, true)
    UserMailer.verified_user(@user).deliver
    redirect_to :back
  end

  def unverify
    User.find(params[:id]).update_attribute(:is_verified, false)
    redirect_to :back
  end
  
  # # GET /users
  # # GET /users.json
  # def index
  #   @users = User.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @users }
  #   end
  # end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end

    authorize! :manage, @user

  end

  def lunch_confirmation
    @user = current_user
  end
  
  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @user.pending_memberships.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])

    authorize! :manage, @user
  end

  # POST /users
  # POST /users.json
  def create

    @pending_membership = PendingMembership.new(club_id: params[:user][:pending_membership][:club_id])

    params[:user].delete("pending_membership")

    @user = User.new(params[:user])
    @possible_memberships = PendingMembership.where(user_email: @user.email)

    if @possible_memberships.length > 0 && @user.save
      new_user = User.last
      @membership = Membership.new
      @membership.user_id = new_user.id
      @membership.club_id = @possible_memberships.first.club_id
      @possible_memberships.first.destroy
      @membership.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Account and membership successfuly created.'
    elsif @user.save
      @pending_membership.user_id = @user.id 
      @pending_membership.user_first_name = @user.first_name
      @pending_membership.user_last_name = @user.last_name
      @pending_membership.user_email = @user.email
      @pending_membership.save
      UserMailer.admin_verification(@pending_membership).deliver
      UserMailer.welcome(@user).deliver
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Account successfuly created.' 
    else
      # needed for render 'new' in case of form errors 
      @user.pending_memberships.build
      render action: "new"
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.haml
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message

  .field
    = f.text_field :first_name, placeholder: "First Name"
  .field
    = f.text_field :last_name, placeholder: "Last Name"
  .field
    = f.text_field :email, placeholder: "Email"

  .field
    = f.password_field :password, placeholder: "Password"
  .field
    = f.password_field :password_confirmation, placeholder: "Confirm Password"
  - if params[:action] == "edit"
    .actions= f.submit "Update Info"
  -else
    .actions= f.submit

app/views/users/edit.haml
%h1 Edit Info
.center-box
  .is-inline-block
    = render 'form'
= link_to 'Back', @user

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/lunch_confirmation.haml
%h1 Lunch request submitted!

%p You should receive an email shortly with your next Friend Over Food.

= link_to "Back.", user_path(@user)

app/views/users/new.haml
%h1 Sign Up
%p Sign ups are currently limited to members of approved clubs. 
%p After submitting your registration, your membership will be verified by the club admin.

.center-box
  .is-inline-block
    = form_for @user do |f|
      - if @user.errors.any?
        .error_messages
          %h2 Form is invalid
          %ul
            - for message in @user.errors.full_messages
              %li= message

      .field
        = f.text_field :first_name, placeholder: "First Name"
      .field
        = f.text_field :last_name, placeholder: "Last Name"

      .field
        = f.fields_for @user.pending_memberships do |m|
          = m.label :club_id, "Select your club."
          = m.collection_select :club_id, Club.all, :id, :name
      / .field
      / = f.select :city, [["New York City", "New York City"], ["Chicago", "Chicago"], ["San Francisco", "San Francisco"]]
      .field
        = f.text_field :email, placeholder: "Email"

      .field
        = f.password_field :password, placeholder: "Password"
      .field
        = f.password_field :password_confirmation, placeholder: "Confirm Password"
      .actions
        = f.submit "Sign up"

app/views/users/show.haml
.profile.is-left

  %h1.is-ta-left 
    = @user.first_name
    = @user.last_name

  - if (Lunch.where(luncher_id: nil, user_id: @user.id).length >= @user.clubs.length)
    %p 
      There are no new people in your clubs to lunch with.
  - else
    %p
      There are still people that you haven't lunched with yet!

      = link_to "Find a new lunch!", lunches_path, class: "is-ta-center submit", :method => :post

  %a.is-block.is-ta-center{:href => "#{edit_user_path(@user)}"} 
    Edit your profile info.

.clubs-list.is-left
  %h2 Your Clubs 
  - if @user.clubs.length == 0
    %p Your club registration is currently being verified.
  - else
    - @user.clubs.each do |c|
      %p 
        %a.club{:href => "#{club_path(c.id)}"} 
          = c.name
  
  %br/ 
  %p.is-ta-center 
    %a.is-inline-block.is-ta-center.submit{:href => "#{clubs_path}"} Join More Clubs