config/routes.rb
FriendOverFood::Application.routes.draw do

  resources :clubs do
    member do
      post 'join'
      post 'approve_membership'
      post 'deny_membership'
    end
  end

  resources :admins do
    member do
    end
  end

  resources :users do
    member do
      get :lunch_confirmation
      post 'verify'
      post 'unverify'
    end
  end

  resources :sessions
  resources :lunches

  resources :pending_memberships
  resources :memberships do
    member do
      post 'make_admin'
    end
  end
  
  get "sign_out" => "sessions#destroy", :as => "sign_out"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match 'contact' => 'home#contact'
  match 'about' => 'home#about'
  match 'faq' => 'home#faq'

  root :to => 'home#index'

end

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title Friend Over Food
    %meta{:content => "Friend Over Food", :property => "og:title"}
    %meta{:content => "http://www.friendoverfood.com/", :property => "og:url"}
    %meta{:content => "#{root_url[0...-1]}#{image_path("og.png")}", :property => "og:image"}
    %meta{:content => "Friend Over Food", :property => "og:site_name"}
    %meta{:content => "Friend Over Food", :property => "og:description"}
    %meta{:content => "Friend Over Food", :itemprop => "name"}
    %meta{:content => "Friend Over Food", :itemprop => "description"}
    %meta{:content => "summary", :name => "twitter:card"}
    %meta{:content => "Friend Over Food", :name => "twitter:title"}
    %meta{:content => "Friend Over Food", :name => "twitter:description"}
    %meta{:content => "Friend Over Food", :name => "description"}
    %meta{:content => "", :name => "keywords"}
    %meta{:name => "mode"}/
    %meta{:content => "friendoverfood", :name => "permalink"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Josefin+Slab:400,700", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Raleway:400,700", :rel => "stylesheet", :type => "text/css"}/
    = favicon_link_tag 'fav.png'
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body

    %header.l-header.clearfix
      %a.logo.is-left{:href => "#{root_path}"} 
        %span.t-medium_blue> FRIEND 
        %span.t-orange> OVER
        %span.t-medium_blue> FOOD 

      %nav.l-header-nav 
        %ul.l-header-nav.is-right
          - if current_user
            %li 
              = link_to "#{current_user.first_name.downcase}", user_path(current_user.id), class: 't-orange'
            %li
              = link_to "sign out", sign_out_path
          - elsif current_admin
            %li 
              = link_to "admin", admin_path(current_admin.id), class: 't-orange'
            %li 
              = link_to "sign out", sign_out_path
          - else
            %li 
              %a{:href => "#{sign_in_path}"} sign in
            %li 
              %a{:href => "#{sign_up_path}"} sign up
          %li 
            %a{:href => "#{contact_path}"} contact
          %li 
            %a{:href => "#{faq_path}"} faq
          %li 
            %a{:href => "#{about_path}"} about
  
    
    - if params[:controller] == "home" && params[:action] == "index" || params[:action] == "show"
      - if flash[:notice]
        %p#notice.is-ta-center= flash[:notice]

      = yield
      
    -else
      .l-container.is-ta-center
        - if flash[:notice]
          %p#notice.is-ta-center= flash[:notice]

        = yield
    
    %footer.l-footer 
      %p 
        ©2013 Friend Over Food, All Rights Reserved 

  / Google Analytics
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46697328-1', 'friendoverfood.com');
    ga('send', 'pageview');